name: 'Create a development build on prerelease'

on:
  release:
    types: [prereleased]

jobs:
  build:
    uses: network-rail-business-systems/workflows/.github/workflows/build-dev.yml@main
    with:
      php: '8.3'
      npm: false
