name: 'Create a production build on release'

on:
  release:
    types: [released]

jobs:
  build:
    uses: network-rail-business-systems/workflows/.github/workflows/build-prod.yml@main
    with:
      php: '8.3'
      npm: false
