name: 'Run tests whenever a pull request is opened'

on: [pull_request]

jobs:
  test:
    uses: network-rail-business-systems/workflows/.github/workflows/unit-tests.yml@main
    with:
      php: '8.3'
      npm: false
